# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1293, 838)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 1271, 811))
        self.tabWidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(86, 164, 158, 255), stop:1 rgba(255, 255, 255, 255));\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.table_keypoint_referans = QtWidgets.QTableWidget(self.tab_4)
        self.table_keypoint_referans.setGeometry(QtCore.QRect(10, 100, 741, 451))
        self.table_keypoint_referans.setObjectName("table_keypoint_referans")
        self.table_keypoint_referans.setColumnCount(0)
        self.table_keypoint_referans.setRowCount(0)
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(20, 70, 221, 16))
        self.label_4.setObjectName("label_4")
        self.btn_keypoint_referance_points = QtWidgets.QPushButton(self.tab_4)
        self.btn_keypoint_referance_points.setGeometry(QtCore.QRect(20, 10, 271, 31))
        self.btn_keypoint_referance_points.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"   background-color:rgb(250, 250, 250);\n"
"}")
        self.btn_keypoint_referance_points.setObjectName("btn_keypoint_referance_points")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 80, 1211, 681))
        self.groupBox_5.setObjectName("groupBox_5")
        self.table_keypoint_result = QtWidgets.QTableWidget(self.groupBox_5)
        self.table_keypoint_result.setGeometry(QtCore.QRect(5, 25, 1181, 621))
        self.table_keypoint_result.setStyleSheet("border:0px;")
        self.table_keypoint_result.setObjectName("table_keypoint_result")
        self.table_keypoint_result.setColumnCount(0)
        self.table_keypoint_result.setRowCount(0)
        self.btn_keypoint_apply = QtWidgets.QPushButton(self.tab)
        self.btn_keypoint_apply.setGeometry(QtCore.QRect(10, 10, 141, 61))
        self.btn_keypoint_apply.setStyleSheet("")
        self.btn_keypoint_apply.setObjectName("btn_keypoint_apply")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setGeometry(QtCore.QRect(30, 70, 1191, 681))
        self.groupBox_6.setObjectName("groupBox_6")
        self.table_keypoint_result_2 = QtWidgets.QTableWidget(self.groupBox_6)
        self.table_keypoint_result_2.setGeometry(QtCore.QRect(5, 25, 1161, 631))
        self.table_keypoint_result_2.setStyleSheet("border:0px;")
        self.table_keypoint_result_2.setObjectName("table_keypoint_result_2")
        self.table_keypoint_result_2.setColumnCount(0)
        self.table_keypoint_result_2.setRowCount(0)
        self.btn_keypoint_apply_2 = QtWidgets.QPushButton(self.tab_2)
        self.btn_keypoint_apply_2.setGeometry(QtCore.QRect(30, 0, 141, 61))
        self.btn_keypoint_apply_2.setStyleSheet("")
        self.btn_keypoint_apply_2.setObjectName("btn_keypoint_apply_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_7.setGeometry(QtCore.QRect(0, 70, 1141, 611))
        self.groupBox_7.setObjectName("groupBox_7")
        self.table_keypoint_result_3 = QtWidgets.QTableWidget(self.groupBox_7)
        self.table_keypoint_result_3.setGeometry(QtCore.QRect(5, 25, 1101, 551))
        self.table_keypoint_result_3.setStyleSheet("border:0px;")
        self.table_keypoint_result_3.setObjectName("table_keypoint_result_3")
        self.table_keypoint_result_3.setColumnCount(0)
        self.table_keypoint_result_3.setRowCount(0)
        self.btn_keypoint_apply_3 = QtWidgets.QPushButton(self.tab_3)
        self.btn_keypoint_apply_3.setGeometry(QtCore.QRect(10, 0, 141, 61))
        self.btn_keypoint_apply_3.setStyleSheet("")
        self.btn_keypoint_apply_3.setObjectName("btn_keypoint_apply_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 10, 241, 231))
        self.groupBox_8.setObjectName("groupBox_8")
        self.img1 = QtWidgets.QGraphicsView(self.groupBox_8)
        self.img1.setGeometry(QtCore.QRect(10, 20, 221, 201))
        self.img1.setStyleSheet("border:0px;")
        self.img1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img1.setObjectName("img1")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_9.setGeometry(QtCore.QRect(260, 10, 241, 231))
        self.groupBox_9.setObjectName("groupBox_9")
        self.img2 = QtWidgets.QGraphicsView(self.groupBox_9)
        self.img2.setGeometry(QtCore.QRect(5, 17, 231, 208))
        self.img2.setStyleSheet("border:0px;")
        self.img2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img2.setObjectName("img2")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_10.setGeometry(QtCore.QRect(510, 10, 241, 231))
        self.groupBox_10.setObjectName("groupBox_10")
        self.img3 = QtWidgets.QGraphicsView(self.groupBox_10)
        self.img3.setGeometry(QtCore.QRect(5, 17, 221, 201))
        self.img3.setStyleSheet("border:0px;")
        self.img3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img3.setObjectName("img3")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_11.setGeometry(QtCore.QRect(760, 10, 241, 231))
        self.groupBox_11.setObjectName("groupBox_11")
        self.img4 = QtWidgets.QGraphicsView(self.groupBox_11)
        self.img4.setGeometry(QtCore.QRect(5, 17, 221, 201))
        self.img4.setStyleSheet("border:0px;")
        self.img4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img4.setObjectName("img4")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_12.setGeometry(QtCore.QRect(1010, 10, 241, 231))
        self.groupBox_12.setObjectName("groupBox_12")
        self.img5 = QtWidgets.QGraphicsView(self.groupBox_12)
        self.img5.setGeometry(QtCore.QRect(5, 17, 221, 201))
        self.img5.setStyleSheet("border:0px;")
        self.img5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img5.setObjectName("img5")
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_13.setGeometry(QtCore.QRect(1010, 370, 241, 231))
        self.groupBox_13.setObjectName("groupBox_13")
        self.img10 = QtWidgets.QGraphicsView(self.groupBox_13)
        self.img10.setGeometry(QtCore.QRect(5, 17, 221, 201))
        self.img10.setStyleSheet("border:0px;")
        self.img10.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img10.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img10.setObjectName("img10")
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_14.setGeometry(QtCore.QRect(260, 370, 241, 231))
        self.groupBox_14.setObjectName("groupBox_14")
        self.img7 = QtWidgets.QGraphicsView(self.groupBox_14)
        self.img7.setGeometry(QtCore.QRect(5, 17, 231, 208))
        self.img7.setStyleSheet("border:0px;")
        self.img7.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img7.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img7.setObjectName("img7")
        self.groupBox_15 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_15.setGeometry(QtCore.QRect(10, 370, 241, 231))
        self.groupBox_15.setObjectName("groupBox_15")
        self.img6 = QtWidgets.QGraphicsView(self.groupBox_15)
        self.img6.setGeometry(QtCore.QRect(5, 17, 221, 201))
        self.img6.setStyleSheet("border:0px;")
        self.img6.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img6.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img6.setObjectName("img6")
        self.groupBox_16 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_16.setGeometry(QtCore.QRect(760, 370, 241, 231))
        self.groupBox_16.setObjectName("groupBox_16")
        self.img9 = QtWidgets.QGraphicsView(self.groupBox_16)
        self.img9.setGeometry(QtCore.QRect(5, 17, 221, 201))
        self.img9.setStyleSheet("border:0px;")
        self.img9.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img9.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img9.setObjectName("img9")
        self.groupBox_17 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_17.setGeometry(QtCore.QRect(510, 370, 241, 231))
        self.groupBox_17.setObjectName("groupBox_17")
        self.img8 = QtWidgets.QGraphicsView(self.groupBox_17)
        self.img8.setGeometry(QtCore.QRect(5, 17, 221, 201))
        self.img8.setStyleSheet("border:0px;")
        self.img8.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img8.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img8.setObjectName("img8")
        self.label_14 = QtWidgets.QLabel(self.tab_5)
        self.label_14.setGeometry(QtCore.QRect(20, 260, 47, 13))
        self.label_14.setObjectName("label_14")
        self.jacdeger1 = QtWidgets.QLabel(self.tab_5)
        self.jacdeger1.setGeometry(QtCore.QRect(80, 260, 141, 21))
        self.jacdeger1.setStyleSheet("")
        self.jacdeger1.setText("")
        self.jacdeger1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger1.setObjectName("jacdeger1")
        self.label_15 = QtWidgets.QLabel(self.tab_5)
        self.label_15.setGeometry(QtCore.QRect(260, 260, 47, 13))
        self.label_15.setObjectName("label_15")
        self.jacdeger2 = QtWidgets.QLabel(self.tab_5)
        self.jacdeger2.setGeometry(QtCore.QRect(320, 260, 141, 21))
        self.jacdeger2.setStyleSheet("")
        self.jacdeger2.setText("")
        self.jacdeger2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger2.setObjectName("jacdeger2")
        self.label_16 = QtWidgets.QLabel(self.tab_5)
        self.label_16.setGeometry(QtCore.QRect(510, 260, 47, 13))
        self.label_16.setObjectName("label_16")
        self.jacdeger3 = QtWidgets.QLabel(self.tab_5)
        self.jacdeger3.setGeometry(QtCore.QRect(570, 260, 141, 21))
        self.jacdeger3.setStyleSheet("")
        self.jacdeger3.setText("")
        self.jacdeger3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger3.setObjectName("jacdeger3")
        self.label_17 = QtWidgets.QLabel(self.tab_5)
        self.label_17.setGeometry(QtCore.QRect(770, 260, 47, 13))
        self.label_17.setObjectName("label_17")
        self.jacdeger4 = QtWidgets.QLabel(self.tab_5)
        self.jacdeger4.setGeometry(QtCore.QRect(830, 260, 141, 21))
        self.jacdeger4.setStyleSheet("")
        self.jacdeger4.setText("")
        self.jacdeger4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger4.setObjectName("jacdeger4")
        self.label_18 = QtWidgets.QLabel(self.tab_5)
        self.label_18.setGeometry(QtCore.QRect(1020, 260, 47, 13))
        self.label_18.setObjectName("label_18")
        self.jacdeger5 = QtWidgets.QLabel(self.tab_5)
        self.jacdeger5.setGeometry(QtCore.QRect(1080, 260, 141, 21))
        self.jacdeger5.setStyleSheet("")
        self.jacdeger5.setText("")
        self.jacdeger5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger5.setObjectName("jacdeger5")
        self.label_19 = QtWidgets.QLabel(self.tab_5)
        self.label_19.setGeometry(QtCore.QRect(20, 620, 47, 13))
        self.label_19.setObjectName("label_19")
        self.jacdeger6 = QtWidgets.QLabel(self.tab_5)
        self.jacdeger6.setGeometry(QtCore.QRect(80, 620, 141, 21))
        self.jacdeger6.setStyleSheet("")
        self.jacdeger6.setText("")
        self.jacdeger6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger6.setObjectName("jacdeger6")
        self.label_20 = QtWidgets.QLabel(self.tab_5)
        self.label_20.setGeometry(QtCore.QRect(270, 620, 47, 13))
        self.label_20.setObjectName("label_20")
        self.jacdeger7 = QtWidgets.QLabel(self.tab_5)
        self.jacdeger7.setGeometry(QtCore.QRect(330, 620, 141, 21))
        self.jacdeger7.setStyleSheet("")
        self.jacdeger7.setText("")
        self.jacdeger7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger7.setObjectName("jacdeger7")
        self.label_21 = QtWidgets.QLabel(self.tab_5)
        self.label_21.setGeometry(QtCore.QRect(520, 620, 47, 13))
        self.label_21.setObjectName("label_21")
        self.jacdeger8 = QtWidgets.QLabel(self.tab_5)
        self.jacdeger8.setGeometry(QtCore.QRect(580, 620, 141, 21))
        self.jacdeger8.setStyleSheet("")
        self.jacdeger8.setText("")
        self.jacdeger8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger8.setObjectName("jacdeger8")
        self.label_22 = QtWidgets.QLabel(self.tab_5)
        self.label_22.setGeometry(QtCore.QRect(770, 620, 47, 13))
        self.label_22.setObjectName("label_22")
        self.jacdeger9 = QtWidgets.QLabel(self.tab_5)
        self.jacdeger9.setGeometry(QtCore.QRect(830, 620, 141, 21))
        self.jacdeger9.setStyleSheet("")
        self.jacdeger9.setText("")
        self.jacdeger9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger9.setObjectName("jacdeger9")
        self.label_23 = QtWidgets.QLabel(self.tab_5)
        self.label_23.setGeometry(QtCore.QRect(1010, 620, 47, 13))
        self.label_23.setObjectName("label_23")
        self.jacdeger10 = QtWidgets.QLabel(self.tab_5)
        self.jacdeger10.setGeometry(QtCore.QRect(1070, 620, 141, 21))
        self.jacdeger10.setStyleSheet("")
        self.jacdeger10.setText("")
        self.jacdeger10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger10.setObjectName("jacdeger10")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.jacdeger12 = QtWidgets.QLabel(self.tab_6)
        self.jacdeger12.setGeometry(QtCore.QRect(320, 260, 141, 21))
        self.jacdeger12.setStyleSheet("")
        self.jacdeger12.setText("")
        self.jacdeger12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger12.setObjectName("jacdeger12")
        self.groupBox_18 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_18.setGeometry(QtCore.QRect(760, 370, 241, 231))
        self.groupBox_18.setObjectName("groupBox_18")
        self.img19 = QtWidgets.QGraphicsView(self.groupBox_18)
        self.img19.setGeometry(QtCore.QRect(5, 17, 221, 201))
        self.img19.setStyleSheet("border:0px;")
        self.img19.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img19.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img19.setObjectName("img19")
        self.jacdeger15 = QtWidgets.QLabel(self.tab_6)
        self.jacdeger15.setGeometry(QtCore.QRect(1080, 260, 141, 21))
        self.jacdeger15.setStyleSheet("")
        self.jacdeger15.setText("")
        self.jacdeger15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger15.setObjectName("jacdeger15")
        self.groupBox_19 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_19.setGeometry(QtCore.QRect(260, 370, 241, 231))
        self.groupBox_19.setObjectName("groupBox_19")
        self.img17 = QtWidgets.QGraphicsView(self.groupBox_19)
        self.img17.setGeometry(QtCore.QRect(5, 17, 231, 208))
        self.img17.setStyleSheet("border:0px;")
        self.img17.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img17.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img17.setObjectName("img17")
        self.groupBox_20 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_20.setGeometry(QtCore.QRect(1010, 370, 241, 231))
        self.groupBox_20.setObjectName("groupBox_20")
        self.img20 = QtWidgets.QGraphicsView(self.groupBox_20)
        self.img20.setGeometry(QtCore.QRect(5, 17, 221, 201))
        self.img20.setStyleSheet("border:0px;")
        self.img20.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img20.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img20.setObjectName("img20")
        self.jacdeger16 = QtWidgets.QLabel(self.tab_6)
        self.jacdeger16.setGeometry(QtCore.QRect(80, 620, 141, 21))
        self.jacdeger16.setStyleSheet("")
        self.jacdeger16.setText("")
        self.jacdeger16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger16.setObjectName("jacdeger16")
        self.jacdeger11 = QtWidgets.QLabel(self.tab_6)
        self.jacdeger11.setGeometry(QtCore.QRect(80, 260, 141, 21))
        self.jacdeger11.setStyleSheet("")
        self.jacdeger11.setText("")
        self.jacdeger11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger11.setObjectName("jacdeger11")
        self.groupBox_21 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_21.setGeometry(QtCore.QRect(510, 10, 241, 231))
        self.groupBox_21.setObjectName("groupBox_21")
        self.img13 = QtWidgets.QGraphicsView(self.groupBox_21)
        self.img13.setGeometry(QtCore.QRect(5, 17, 221, 201))
        self.img13.setStyleSheet("border:0px;")
        self.img13.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img13.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img13.setObjectName("img13")
        self.jacdeger19 = QtWidgets.QLabel(self.tab_6)
        self.jacdeger19.setGeometry(QtCore.QRect(830, 620, 141, 21))
        self.jacdeger19.setStyleSheet("")
        self.jacdeger19.setText("")
        self.jacdeger19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger19.setObjectName("jacdeger19")
        self.jacdeger14 = QtWidgets.QLabel(self.tab_6)
        self.jacdeger14.setGeometry(QtCore.QRect(830, 260, 141, 21))
        self.jacdeger14.setStyleSheet("")
        self.jacdeger14.setText("")
        self.jacdeger14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger14.setObjectName("jacdeger14")
        self.groupBox_22 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_22.setGeometry(QtCore.QRect(260, 10, 241, 231))
        self.groupBox_22.setObjectName("groupBox_22")
        self.img12 = QtWidgets.QGraphicsView(self.groupBox_22)
        self.img12.setGeometry(QtCore.QRect(5, 17, 231, 208))
        self.img12.setStyleSheet("border:0px;")
        self.img12.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img12.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img12.setObjectName("img12")
        self.jacdeger20 = QtWidgets.QLabel(self.tab_6)
        self.jacdeger20.setGeometry(QtCore.QRect(1070, 620, 141, 21))
        self.jacdeger20.setStyleSheet("")
        self.jacdeger20.setText("")
        self.jacdeger20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger20.setObjectName("jacdeger20")
        self.groupBox_23 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_23.setGeometry(QtCore.QRect(510, 370, 241, 231))
        self.groupBox_23.setObjectName("groupBox_23")
        self.img18 = QtWidgets.QGraphicsView(self.groupBox_23)
        self.img18.setGeometry(QtCore.QRect(5, 17, 221, 201))
        self.img18.setStyleSheet("border:0px;")
        self.img18.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img18.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img18.setObjectName("img18")
        self.groupBox_24 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_24.setGeometry(QtCore.QRect(10, 370, 241, 231))
        self.groupBox_24.setObjectName("groupBox_24")
        self.img16 = QtWidgets.QGraphicsView(self.groupBox_24)
        self.img16.setGeometry(QtCore.QRect(5, 17, 221, 201))
        self.img16.setStyleSheet("border:0px;")
        self.img16.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img16.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img16.setObjectName("img16")
        self.jacdeger17 = QtWidgets.QLabel(self.tab_6)
        self.jacdeger17.setGeometry(QtCore.QRect(330, 620, 141, 21))
        self.jacdeger17.setStyleSheet("")
        self.jacdeger17.setText("")
        self.jacdeger17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger17.setObjectName("jacdeger17")
        self.jacdeger13 = QtWidgets.QLabel(self.tab_6)
        self.jacdeger13.setGeometry(QtCore.QRect(570, 260, 141, 21))
        self.jacdeger13.setStyleSheet("")
        self.jacdeger13.setText("")
        self.jacdeger13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger13.setObjectName("jacdeger13")
        self.jacdeger18 = QtWidgets.QLabel(self.tab_6)
        self.jacdeger18.setGeometry(QtCore.QRect(580, 620, 141, 21))
        self.jacdeger18.setStyleSheet("")
        self.jacdeger18.setText("")
        self.jacdeger18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger18.setObjectName("jacdeger18")
        self.groupBox_25 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_25.setGeometry(QtCore.QRect(760, 10, 241, 231))
        self.groupBox_25.setObjectName("groupBox_25")
        self.img14 = QtWidgets.QGraphicsView(self.groupBox_25)
        self.img14.setGeometry(QtCore.QRect(5, 17, 221, 201))
        self.img14.setStyleSheet("border:0px;")
        self.img14.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img14.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img14.setObjectName("img14")
        self.groupBox_26 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_26.setGeometry(QtCore.QRect(10, 10, 241, 231))
        self.groupBox_26.setObjectName("groupBox_26")
        self.img11 = QtWidgets.QGraphicsView(self.groupBox_26)
        self.img11.setGeometry(QtCore.QRect(10, 20, 221, 201))
        self.img11.setStyleSheet("border:0px;")
        self.img11.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img11.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img11.setObjectName("img11")
        self.groupBox_27 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_27.setGeometry(QtCore.QRect(1010, 10, 241, 231))
        self.groupBox_27.setObjectName("groupBox_27")
        self.img15 = QtWidgets.QGraphicsView(self.groupBox_27)
        self.img15.setGeometry(QtCore.QRect(5, 17, 221, 201))
        self.img15.setStyleSheet("border:0px;")
        self.img15.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img15.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img15.setObjectName("img15")
        self.label_24 = QtWidgets.QLabel(self.tab_6)
        self.label_24.setGeometry(QtCore.QRect(510, 260, 47, 13))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.tab_6)
        self.label_25.setGeometry(QtCore.QRect(20, 260, 47, 13))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tab_6)
        self.label_26.setGeometry(QtCore.QRect(770, 620, 47, 13))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.tab_6)
        self.label_27.setGeometry(QtCore.QRect(260, 260, 47, 13))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.tab_6)
        self.label_28.setGeometry(QtCore.QRect(770, 260, 47, 13))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.tab_6)
        self.label_29.setGeometry(QtCore.QRect(20, 620, 47, 13))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.tab_6)
        self.label_30.setGeometry(QtCore.QRect(270, 620, 47, 13))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.tab_6)
        self.label_31.setGeometry(QtCore.QRect(520, 620, 47, 13))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.tab_6)
        self.label_32.setGeometry(QtCore.QRect(1020, 260, 47, 13))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.tab_6)
        self.label_33.setGeometry(QtCore.QRect(1010, 620, 47, 13))
        self.label_33.setObjectName("label_33")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.jacdeger22 = QtWidgets.QLabel(self.tab_7)
        self.jacdeger22.setGeometry(QtCore.QRect(320, 260, 141, 21))
        self.jacdeger22.setStyleSheet("")
        self.jacdeger22.setText("")
        self.jacdeger22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger22.setObjectName("jacdeger22")
        self.groupBox_28 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_28.setGeometry(QtCore.QRect(760, 370, 241, 231))
        self.groupBox_28.setObjectName("groupBox_28")
        self.img29 = QtWidgets.QGraphicsView(self.groupBox_28)
        self.img29.setGeometry(QtCore.QRect(5, 17, 221, 201))
        self.img29.setStyleSheet("border:0px;")
        self.img29.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img29.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img29.setObjectName("img29")
        self.jacdeger25 = QtWidgets.QLabel(self.tab_7)
        self.jacdeger25.setGeometry(QtCore.QRect(1080, 260, 141, 21))
        self.jacdeger25.setStyleSheet("")
        self.jacdeger25.setText("")
        self.jacdeger25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger25.setObjectName("jacdeger25")
        self.groupBox_29 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_29.setGeometry(QtCore.QRect(260, 370, 241, 231))
        self.groupBox_29.setObjectName("groupBox_29")
        self.img27 = QtWidgets.QGraphicsView(self.groupBox_29)
        self.img27.setGeometry(QtCore.QRect(5, 17, 231, 208))
        self.img27.setStyleSheet("border:0px;")
        self.img27.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img27.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img27.setObjectName("img27")
        self.groupBox_30 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_30.setGeometry(QtCore.QRect(1010, 370, 241, 231))
        self.groupBox_30.setObjectName("groupBox_30")
        self.img30 = QtWidgets.QGraphicsView(self.groupBox_30)
        self.img30.setGeometry(QtCore.QRect(5, 17, 221, 201))
        self.img30.setStyleSheet("border:0px;")
        self.img30.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img30.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img30.setObjectName("img30")
        self.jacdeger26 = QtWidgets.QLabel(self.tab_7)
        self.jacdeger26.setGeometry(QtCore.QRect(80, 620, 141, 21))
        self.jacdeger26.setStyleSheet("")
        self.jacdeger26.setText("")
        self.jacdeger26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger26.setObjectName("jacdeger26")
        self.jacdeger21 = QtWidgets.QLabel(self.tab_7)
        self.jacdeger21.setGeometry(QtCore.QRect(80, 260, 141, 21))
        self.jacdeger21.setStyleSheet("")
        self.jacdeger21.setText("")
        self.jacdeger21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger21.setObjectName("jacdeger21")
        self.groupBox_31 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_31.setGeometry(QtCore.QRect(510, 10, 241, 231))
        self.groupBox_31.setObjectName("groupBox_31")
        self.img23 = QtWidgets.QGraphicsView(self.groupBox_31)
        self.img23.setGeometry(QtCore.QRect(5, 17, 221, 201))
        self.img23.setStyleSheet("border:0px;")
        self.img23.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img23.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img23.setObjectName("img23")
        self.jacdeger29 = QtWidgets.QLabel(self.tab_7)
        self.jacdeger29.setGeometry(QtCore.QRect(830, 620, 141, 21))
        self.jacdeger29.setStyleSheet("")
        self.jacdeger29.setText("")
        self.jacdeger29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger29.setObjectName("jacdeger29")
        self.jacdeger24 = QtWidgets.QLabel(self.tab_7)
        self.jacdeger24.setGeometry(QtCore.QRect(830, 260, 141, 21))
        self.jacdeger24.setStyleSheet("")
        self.jacdeger24.setText("")
        self.jacdeger24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger24.setObjectName("jacdeger24")
        self.groupBox_32 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_32.setGeometry(QtCore.QRect(260, 10, 241, 231))
        self.groupBox_32.setObjectName("groupBox_32")
        self.img22 = QtWidgets.QGraphicsView(self.groupBox_32)
        self.img22.setGeometry(QtCore.QRect(5, 17, 231, 208))
        self.img22.setStyleSheet("border:0px;")
        self.img22.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img22.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img22.setObjectName("img22")
        self.jacdeger30 = QtWidgets.QLabel(self.tab_7)
        self.jacdeger30.setGeometry(QtCore.QRect(1070, 620, 141, 21))
        self.jacdeger30.setStyleSheet("")
        self.jacdeger30.setText("")
        self.jacdeger30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger30.setObjectName("jacdeger30")
        self.groupBox_33 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_33.setGeometry(QtCore.QRect(510, 370, 241, 231))
        self.groupBox_33.setObjectName("groupBox_33")
        self.img28 = QtWidgets.QGraphicsView(self.groupBox_33)
        self.img28.setGeometry(QtCore.QRect(5, 17, 221, 201))
        self.img28.setStyleSheet("border:0px;")
        self.img28.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img28.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img28.setObjectName("img28")
        self.groupBox_34 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_34.setGeometry(QtCore.QRect(10, 370, 241, 231))
        self.groupBox_34.setObjectName("groupBox_34")
        self.img26 = QtWidgets.QGraphicsView(self.groupBox_34)
        self.img26.setGeometry(QtCore.QRect(5, 17, 221, 201))
        self.img26.setStyleSheet("border:0px;")
        self.img26.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img26.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img26.setObjectName("img26")
        self.jacdeger27 = QtWidgets.QLabel(self.tab_7)
        self.jacdeger27.setGeometry(QtCore.QRect(330, 620, 141, 21))
        self.jacdeger27.setStyleSheet("")
        self.jacdeger27.setText("")
        self.jacdeger27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger27.setObjectName("jacdeger27")
        self.jacdeger23 = QtWidgets.QLabel(self.tab_7)
        self.jacdeger23.setGeometry(QtCore.QRect(570, 260, 141, 21))
        self.jacdeger23.setStyleSheet("")
        self.jacdeger23.setText("")
        self.jacdeger23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger23.setObjectName("jacdeger23")
        self.jacdeger28 = QtWidgets.QLabel(self.tab_7)
        self.jacdeger28.setGeometry(QtCore.QRect(580, 620, 141, 21))
        self.jacdeger28.setStyleSheet("")
        self.jacdeger28.setText("")
        self.jacdeger28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger28.setObjectName("jacdeger28")
        self.groupBox_35 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_35.setGeometry(QtCore.QRect(760, 10, 241, 231))
        self.groupBox_35.setObjectName("groupBox_35")
        self.img24 = QtWidgets.QGraphicsView(self.groupBox_35)
        self.img24.setGeometry(QtCore.QRect(5, 17, 221, 201))
        self.img24.setStyleSheet("border:0px;")
        self.img24.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img24.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img24.setObjectName("img24")
        self.groupBox_36 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_36.setGeometry(QtCore.QRect(10, 10, 241, 231))
        self.groupBox_36.setObjectName("groupBox_36")
        self.img21 = QtWidgets.QGraphicsView(self.groupBox_36)
        self.img21.setGeometry(QtCore.QRect(10, 20, 221, 201))
        self.img21.setStyleSheet("border:0px;")
        self.img21.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img21.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img21.setObjectName("img21")
        self.groupBox_37 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_37.setGeometry(QtCore.QRect(1010, 10, 241, 231))
        self.groupBox_37.setObjectName("groupBox_37")
        self.img25 = QtWidgets.QGraphicsView(self.groupBox_37)
        self.img25.setGeometry(QtCore.QRect(5, 17, 221, 201))
        self.img25.setStyleSheet("border:0px;")
        self.img25.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img25.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img25.setObjectName("img25")
        self.label_34 = QtWidgets.QLabel(self.tab_7)
        self.label_34.setGeometry(QtCore.QRect(510, 260, 47, 13))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.tab_7)
        self.label_35.setGeometry(QtCore.QRect(20, 260, 47, 13))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.tab_7)
        self.label_36.setGeometry(QtCore.QRect(770, 620, 47, 13))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.tab_7)
        self.label_37.setGeometry(QtCore.QRect(260, 260, 47, 13))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.tab_7)
        self.label_38.setGeometry(QtCore.QRect(770, 260, 47, 13))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.tab_7)
        self.label_39.setGeometry(QtCore.QRect(20, 620, 47, 13))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.tab_7)
        self.label_40.setGeometry(QtCore.QRect(270, 620, 47, 13))
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.tab_7)
        self.label_41.setGeometry(QtCore.QRect(520, 620, 47, 13))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.tab_7)
        self.label_42.setGeometry(QtCore.QRect(1020, 260, 47, 13))
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.tab_7)
        self.label_43.setGeometry(QtCore.QRect(1010, 620, 47, 13))
        self.label_43.setObjectName("label_43")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.jacdeger32 = QtWidgets.QLabel(self.tab_8)
        self.jacdeger32.setGeometry(QtCore.QRect(320, 250, 141, 21))
        self.jacdeger32.setStyleSheet("")
        self.jacdeger32.setText("")
        self.jacdeger32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger32.setObjectName("jacdeger32")
        self.groupBox_38 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_38.setGeometry(QtCore.QRect(760, 360, 241, 231))
        self.groupBox_38.setObjectName("groupBox_38")
        self.img39 = QtWidgets.QGraphicsView(self.groupBox_38)
        self.img39.setGeometry(QtCore.QRect(5, 17, 221, 201))
        self.img39.setStyleSheet("border:0px;")
        self.img39.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img39.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img39.setObjectName("img39")
        self.jacdeger35 = QtWidgets.QLabel(self.tab_8)
        self.jacdeger35.setGeometry(QtCore.QRect(1080, 250, 141, 21))
        self.jacdeger35.setStyleSheet("")
        self.jacdeger35.setText("")
        self.jacdeger35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger35.setObjectName("jacdeger35")
        self.groupBox_39 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_39.setGeometry(QtCore.QRect(260, 360, 241, 231))
        self.groupBox_39.setObjectName("groupBox_39")
        self.img37 = QtWidgets.QGraphicsView(self.groupBox_39)
        self.img37.setGeometry(QtCore.QRect(5, 17, 231, 208))
        self.img37.setStyleSheet("border:0px;")
        self.img37.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img37.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img37.setObjectName("img37")
        self.groupBox_40 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_40.setGeometry(QtCore.QRect(1010, 360, 241, 231))
        self.groupBox_40.setObjectName("groupBox_40")
        self.img40 = QtWidgets.QGraphicsView(self.groupBox_40)
        self.img40.setGeometry(QtCore.QRect(5, 17, 221, 201))
        self.img40.setStyleSheet("border:0px;")
        self.img40.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img40.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img40.setObjectName("img40")
        self.jacdeger36 = QtWidgets.QLabel(self.tab_8)
        self.jacdeger36.setGeometry(QtCore.QRect(80, 610, 141, 21))
        self.jacdeger36.setStyleSheet("")
        self.jacdeger36.setText("")
        self.jacdeger36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger36.setObjectName("jacdeger36")
        self.jacdeger31 = QtWidgets.QLabel(self.tab_8)
        self.jacdeger31.setGeometry(QtCore.QRect(80, 250, 141, 21))
        self.jacdeger31.setStyleSheet("")
        self.jacdeger31.setText("")
        self.jacdeger31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger31.setObjectName("jacdeger31")
        self.groupBox_41 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_41.setGeometry(QtCore.QRect(510, 0, 241, 231))
        self.groupBox_41.setObjectName("groupBox_41")
        self.img33 = QtWidgets.QGraphicsView(self.groupBox_41)
        self.img33.setGeometry(QtCore.QRect(5, 17, 221, 201))
        self.img33.setStyleSheet("border:0px;")
        self.img33.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img33.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img33.setObjectName("img33")
        self.jacdeger39 = QtWidgets.QLabel(self.tab_8)
        self.jacdeger39.setGeometry(QtCore.QRect(830, 610, 141, 21))
        self.jacdeger39.setStyleSheet("")
        self.jacdeger39.setText("")
        self.jacdeger39.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger39.setObjectName("jacdeger39")
        self.jacdeger34 = QtWidgets.QLabel(self.tab_8)
        self.jacdeger34.setGeometry(QtCore.QRect(830, 250, 141, 21))
        self.jacdeger34.setStyleSheet("")
        self.jacdeger34.setText("")
        self.jacdeger34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger34.setObjectName("jacdeger34")
        self.groupBox_42 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_42.setGeometry(QtCore.QRect(260, 0, 241, 231))
        self.groupBox_42.setObjectName("groupBox_42")
        self.img32 = QtWidgets.QGraphicsView(self.groupBox_42)
        self.img32.setGeometry(QtCore.QRect(5, 17, 231, 208))
        self.img32.setStyleSheet("border:0px;")
        self.img32.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img32.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img32.setObjectName("img32")
        self.jacdeger40 = QtWidgets.QLabel(self.tab_8)
        self.jacdeger40.setGeometry(QtCore.QRect(1070, 610, 141, 21))
        self.jacdeger40.setStyleSheet("")
        self.jacdeger40.setText("")
        self.jacdeger40.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger40.setObjectName("jacdeger40")
        self.groupBox_43 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_43.setGeometry(QtCore.QRect(510, 360, 241, 231))
        self.groupBox_43.setObjectName("groupBox_43")
        self.img38 = QtWidgets.QGraphicsView(self.groupBox_43)
        self.img38.setGeometry(QtCore.QRect(5, 17, 221, 201))
        self.img38.setStyleSheet("border:0px;")
        self.img38.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img38.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img38.setObjectName("img38")
        self.groupBox_44 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_44.setGeometry(QtCore.QRect(10, 360, 241, 231))
        self.groupBox_44.setObjectName("groupBox_44")
        self.img36 = QtWidgets.QGraphicsView(self.groupBox_44)
        self.img36.setGeometry(QtCore.QRect(5, 17, 221, 201))
        self.img36.setStyleSheet("border:0px;")
        self.img36.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img36.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img36.setObjectName("img36")
        self.jacdeger37 = QtWidgets.QLabel(self.tab_8)
        self.jacdeger37.setGeometry(QtCore.QRect(330, 610, 141, 21))
        self.jacdeger37.setStyleSheet("")
        self.jacdeger37.setText("")
        self.jacdeger37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger37.setObjectName("jacdeger37")
        self.jacdeger33 = QtWidgets.QLabel(self.tab_8)
        self.jacdeger33.setGeometry(QtCore.QRect(570, 250, 141, 21))
        self.jacdeger33.setStyleSheet("")
        self.jacdeger33.setText("")
        self.jacdeger33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger33.setObjectName("jacdeger33")
        self.jacdeger38 = QtWidgets.QLabel(self.tab_8)
        self.jacdeger38.setGeometry(QtCore.QRect(580, 610, 141, 21))
        self.jacdeger38.setStyleSheet("")
        self.jacdeger38.setText("")
        self.jacdeger38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jacdeger38.setObjectName("jacdeger38")
        self.groupBox_45 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_45.setGeometry(QtCore.QRect(760, 0, 241, 231))
        self.groupBox_45.setObjectName("groupBox_45")
        self.img34 = QtWidgets.QGraphicsView(self.groupBox_45)
        self.img34.setGeometry(QtCore.QRect(5, 17, 221, 201))
        self.img34.setStyleSheet("border:0px;")
        self.img34.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img34.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img34.setObjectName("img34")
        self.groupBox_46 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_46.setGeometry(QtCore.QRect(10, 0, 241, 231))
        self.groupBox_46.setObjectName("groupBox_46")
        self.img31 = QtWidgets.QGraphicsView(self.groupBox_46)
        self.img31.setGeometry(QtCore.QRect(10, 20, 221, 201))
        self.img31.setStyleSheet("border:0px;")
        self.img31.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img31.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img31.setObjectName("img31")
        self.groupBox_47 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_47.setGeometry(QtCore.QRect(1010, 0, 241, 231))
        self.groupBox_47.setObjectName("groupBox_47")
        self.img35 = QtWidgets.QGraphicsView(self.groupBox_47)
        self.img35.setGeometry(QtCore.QRect(5, 17, 221, 201))
        self.img35.setStyleSheet("border:0px;")
        self.img35.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img35.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.img35.setObjectName("img35")
        self.label_44 = QtWidgets.QLabel(self.tab_8)
        self.label_44.setGeometry(QtCore.QRect(500, 250, 47, 13))
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.tab_8)
        self.label_45.setGeometry(QtCore.QRect(10, 250, 47, 13))
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.tab_8)
        self.label_46.setGeometry(QtCore.QRect(760, 610, 47, 13))
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.tab_8)
        self.label_47.setGeometry(QtCore.QRect(250, 250, 47, 13))
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.tab_8)
        self.label_48.setGeometry(QtCore.QRect(760, 250, 47, 13))
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.tab_8)
        self.label_49.setGeometry(QtCore.QRect(10, 610, 47, 13))
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.tab_8)
        self.label_50.setGeometry(QtCore.QRect(260, 610, 47, 13))
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.tab_8)
        self.label_51.setGeometry(QtCore.QRect(510, 610, 47, 13))
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.tab_8)
        self.label_52.setGeometry(QtCore.QRect(1010, 250, 47, 13))
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.tab_8)
        self.label_53.setGeometry(QtCore.QRect(1000, 610, 47, 13))
        self.label_53.setObjectName("label_53")
        self.tabWidget.addTab(self.tab_8, "")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "KOORDİNATLAR"))
        self.btn_keypoint_referance_points.setText(_translate("MainWindow", "VERİLERİ YÜKLE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Key Point"))
        self.groupBox_5.setTitle(_translate("MainWindow", "S o n u ç l a r"))
        self.btn_keypoint_apply.setText(_translate("MainWindow", "SURF U Y G U L A"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "SURF"))
        self.groupBox_6.setTitle(_translate("MainWindow", "S o n u ç l a r"))
        self.btn_keypoint_apply_2.setText(_translate("MainWindow", "SIFT UY G U L A"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "SIFT"))
        self.groupBox_7.setTitle(_translate("MainWindow", "S o n u ç l a r"))
        self.btn_keypoint_apply_3.setText(_translate("MainWindow", "ORB UY G U L A"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "ORB"))
        self.groupBox_8.setTitle(_translate("MainWindow", "resim1"))
        self.groupBox_9.setTitle(_translate("MainWindow", "resim2"))
        self.groupBox_10.setTitle(_translate("MainWindow", "resim3"))
        self.groupBox_11.setTitle(_translate("MainWindow", "resim4"))
        self.groupBox_12.setTitle(_translate("MainWindow", "resim5"))
        self.groupBox_13.setTitle(_translate("MainWindow", "resim10"))
        self.groupBox_14.setTitle(_translate("MainWindow", "resim7"))
        self.groupBox_15.setTitle(_translate("MainWindow", "resim6"))
        self.groupBox_16.setTitle(_translate("MainWindow", "resim9"))
        self.groupBox_17.setTitle(_translate("MainWindow", "resim8"))
        self.label_14.setText(_translate("MainWindow", "Jaccard :"))
        self.label_15.setText(_translate("MainWindow", "Jaccard :"))
        self.label_16.setText(_translate("MainWindow", "Jaccard :"))
        self.label_17.setText(_translate("MainWindow", "Jaccard :"))
        self.label_18.setText(_translate("MainWindow", "Jaccard :"))
        self.label_19.setText(_translate("MainWindow", "Jaccard :"))
        self.label_20.setText(_translate("MainWindow", "Jaccard :"))
        self.label_21.setText(_translate("MainWindow", "Jaccard :"))
        self.label_22.setText(_translate("MainWindow", "Jaccard :"))
        self.label_23.setText(_translate("MainWindow", "Jaccard :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "1. resim grubu"))
        self.groupBox_18.setTitle(_translate("MainWindow", "resim9"))
        self.groupBox_19.setTitle(_translate("MainWindow", "resim7"))
        self.groupBox_20.setTitle(_translate("MainWindow", "resim10"))
        self.groupBox_21.setTitle(_translate("MainWindow", "resim3"))
        self.groupBox_22.setTitle(_translate("MainWindow", "resim2"))
        self.groupBox_23.setTitle(_translate("MainWindow", "resim8"))
        self.groupBox_24.setTitle(_translate("MainWindow", "resim6"))
        self.groupBox_25.setTitle(_translate("MainWindow", "resim4"))
        self.groupBox_26.setTitle(_translate("MainWindow", "resim1"))
        self.groupBox_27.setTitle(_translate("MainWindow", "resim5"))
        self.label_24.setText(_translate("MainWindow", "Jaccard :"))
        self.label_25.setText(_translate("MainWindow", "Jaccard :"))
        self.label_26.setText(_translate("MainWindow", "Jaccard :"))
        self.label_27.setText(_translate("MainWindow", "Jaccard :"))
        self.label_28.setText(_translate("MainWindow", "Jaccard :"))
        self.label_29.setText(_translate("MainWindow", "Jaccard :"))
        self.label_30.setText(_translate("MainWindow", "Jaccard :"))
        self.label_31.setText(_translate("MainWindow", "Jaccard :"))
        self.label_32.setText(_translate("MainWindow", "Jaccard :"))
        self.label_33.setText(_translate("MainWindow", "Jaccard :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "2. resim grubu"))
        self.groupBox_28.setTitle(_translate("MainWindow", "resim9"))
        self.groupBox_29.setTitle(_translate("MainWindow", "resim7"))
        self.groupBox_30.setTitle(_translate("MainWindow", "resim10"))
        self.groupBox_31.setTitle(_translate("MainWindow", "resim3"))
        self.groupBox_32.setTitle(_translate("MainWindow", "resim2"))
        self.groupBox_33.setTitle(_translate("MainWindow", "resim8"))
        self.groupBox_34.setTitle(_translate("MainWindow", "resim6"))
        self.groupBox_35.setTitle(_translate("MainWindow", "resim4"))
        self.groupBox_36.setTitle(_translate("MainWindow", "resim1"))
        self.groupBox_37.setTitle(_translate("MainWindow", "resim5"))
        self.label_34.setText(_translate("MainWindow", "Jaccard :"))
        self.label_35.setText(_translate("MainWindow", "Jaccard :"))
        self.label_36.setText(_translate("MainWindow", "Jaccard :"))
        self.label_37.setText(_translate("MainWindow", "Jaccard :"))
        self.label_38.setText(_translate("MainWindow", "Jaccard :"))
        self.label_39.setText(_translate("MainWindow", "Jaccard :"))
        self.label_40.setText(_translate("MainWindow", "Jaccard :"))
        self.label_41.setText(_translate("MainWindow", "Jaccard :"))
        self.label_42.setText(_translate("MainWindow", "Jaccard :"))
        self.label_43.setText(_translate("MainWindow", "Jaccard :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "3. resim grubu"))
        self.groupBox_38.setTitle(_translate("MainWindow", "resim9"))
        self.groupBox_39.setTitle(_translate("MainWindow", "resim7"))
        self.groupBox_40.setTitle(_translate("MainWindow", "resim10"))
        self.groupBox_41.setTitle(_translate("MainWindow", "resim3"))
        self.groupBox_42.setTitle(_translate("MainWindow", "resim2"))
        self.groupBox_43.setTitle(_translate("MainWindow", "resim8"))
        self.groupBox_44.setTitle(_translate("MainWindow", "resim6"))
        self.groupBox_45.setTitle(_translate("MainWindow", "resim4"))
        self.groupBox_46.setTitle(_translate("MainWindow", "resim1"))
        self.groupBox_47.setTitle(_translate("MainWindow", "resim5"))
        self.label_44.setText(_translate("MainWindow", "Jaccard :"))
        self.label_45.setText(_translate("MainWindow", "Jaccard :"))
        self.label_46.setText(_translate("MainWindow", "Jaccard :"))
        self.label_47.setText(_translate("MainWindow", "Jaccard :"))
        self.label_48.setText(_translate("MainWindow", "Jaccard :"))
        self.label_49.setText(_translate("MainWindow", "Jaccard :"))
        self.label_50.setText(_translate("MainWindow", "Jaccard :"))
        self.label_51.setText(_translate("MainWindow", "Jaccard :"))
        self.label_52.setText(_translate("MainWindow", "Jaccard :"))
        self.label_53.setText(_translate("MainWindow", "Jaccard :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "4. resim grubu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

